In [2]:
import numpy as np

In [2]:
# We create a 5 x 5 ndarray that contains integers from 0 to 24
X = np.arange(25).reshape(5, 5)

# We print X
print()
print('Original X = \n', X)
print()

# We use Boolean indexing to select elements in X:
print('The elements in X that are greater than 10:', X[X > 10])
print('The elements in X that lees than or equal to 7:', X[X <= 7])
print('The elements in X that are between 10 and 17:', X[(X > 10) & (X < 17)])

# We use Boolean indexing to assign the elements that are between 10 and 17 the value of -1
X[(X > 10) & (X < 17)] = -1

# We print X
print()
print('X = \n', X)
print()

()
('Original X = \n', array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]]))
()
('The elements in X that are greater than 10:', array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]))
('The elements in X that lees than or equal to 7:', array([0, 1, 2, 3, 4, 5, 6, 7]))
('The elements in X that are between 10 and 17:', array([11, 12, 13, 14, 15, 16]))
()
('X = \n', array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, -1, -1, -1, -1],
       [-1, -1, 17, 18, 19],
       [20, 21, 22, 23, 24]]))
()


In [3]:
# We create a rank 1 ndarray
x = np.array([1,2,3,4,5])

# We create a rank 1 ndarray
y = np.array([6,7,2,8,4])

# We print x
print()
print('x = ', x)

# We print y
print()
print('y = ', y)

# We use set operations to compare x and y:
print()
print('The elements that are both in x and y:', np.intersect1d(x,y))
print('The elements that are in x that are not in y:', np.setdiff1d(x,y))
print('All the elements of x and y:',np.union1d(x,y))


x =  [1 2 3 4 5]

y =  [6 7 2 8 4]

The elements that are both in x and y: [2 4]
The elements that are in x that are not in y: [1 3 5]
All the elements of x and y: [1 2 3 4 5 6 7 8]


In [4]:
# We create an unsorted rank 1 ndarray
x = np.random.randint(1,11,size=(10,))

# We print x
print()
print('Original x = ', x)

# We sort x and print the sorted array using sort as a function.
print()
print('Sorted x (out of place):', np.sort(x))

# When we sort out of place the original array remains intact. To see this we print x again
print()
print('x after sorting:', x)


Original x =  [ 2  2  3  4  2  7 10  1  5  6]

Sorted x (out of place): [ 1  2  2  2  3  4  5  6  7 10]

x after sorting: [ 2  2  3  4  2  7 10  1  5  6]


In [5]:
# We create an unsorted rank 1 ndarray
x = np.random.randint(1,11,size=(10,))

# We print x
print()
print('Original x = ', x)

# We sort x and print the sorted array using sort as a method.
x.sort()

# When we sort in place the original array is changed to the sorted array. To see this we print x again
print()
print('x after sorting:', x)


Original x =  [9 5 4 8 3 2 8 6 2 3]

x after sorting: [2 2 3 3 4 5 6 8 8 9]


In [6]:
# We create an unsorted rank 2 ndarray
X = np.random.randint(1,11,size=(5,5))

# We print X
print()
print('Original X = \n', X)
print()

# We sort the columns of X and print the sorted array
print()
print('X with sorted columns :\n', np.sort(X, axis = 0))

# We sort the rows of X and print the sorted array
print()
print('X with sorted rows :\n', np.sort(X, axis = 1))


Original X = 
 [[ 4  5  5  6  4]
 [ 9  7 10  9  1]
 [ 2  7  3  5  5]
 [ 2  1  3  3  5]
 [ 7  9  1  9  4]]


X with sorted columns :
 [[ 2  1  1  3  1]
 [ 2  5  3  5  4]
 [ 4  7  3  6  4]
 [ 7  7  5  9  5]
 [ 9  9 10  9  5]]

X with sorted rows :
 [[ 4  4  5  5  6]
 [ 1  7  9  9 10]
 [ 2  3  5  5  7]
 [ 1  2  3  3  5]
 [ 1  4  7  9  9]]
